### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [kdeldycke/awesome-iam#112]
Hi, I found some broken links:

- [x] https://www.mobsec.ruhr-uni-bochum.de/media/mobsec/veroeffentlichungen/2019/02/20/usec2019-30-wip-fallback-long-term-study-finalv2.pdf (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [x] https://www.loginradius.com/engineering/blog/pkce/ (file: README.md, status code: 404)
- [x] https://blog.bren2010.io/2014/12/04/macaroons.html (file: README.md, status code: 404)
- [x] https://twosided.substack.com/p/keep-out-the-bad-apples-how-to-moderate (file: README.md, status code: 404)
- [x] https://www.private-ai.ca/PETs_Decision_Tree.png (file: README.md, error: ECONNRESET)
- [x] https://aircloak.com/wp-content/uploads/apf17-reprint.pdf (file: README.md, status code: 404)
- [x] https://shipyourenemiesgdpr.com (file: README.md, error: ENOTFOUND)
- [x] https://amzn.com/0778324338/?tag=kevideld-20 (file: README.md, status code: 404)

**Comment by kdeldycke** [comment]
Thanks @ndsvw for the report!
