### ISSUE TITLE
Add ConsoleMe to policy tools

### ISSUE THREAD

**Issue by tillepille** [kdeldycke/awesome-iam#68]
#### Preliminary checks

* [x] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-iam/blob/main/.github/code-of-conduct.md)
* [x] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-iam/blob/main/.github/contributing.md)
* [x] I have checked there is not other [Issues](https://github.com/kdeldycke/awesome-iam/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-iam/pulls) covering the same topic to open

#### Summary

Explain the motivation for making this change. What does does this bring to the table?

Some time ago Netflix announced their policy tool [ConsoleMe](https://github.com/Netflix/consoleme) with [this blogpost](https://netflixtechblog.com/consoleme-a-central-control-plane-for-aws-permissions-and-access-fd09afdd60a8).

Quoting the article

> ConsoleMe is a self-service tool for AWS that provides an easier way of managing permissions and access across multiple accounts, while encouraging least-privilege permissions

I think this fits nicely into the list of [policy tools](https://github.com/kdeldycke/awesome-iam#aws-policy-tools).

If accepted I would contribute a PR for it.

**Comment by kdeldycke** [comment]
ConsoleMe is actively maintained so yes, it is a good candidate! As it is AWS-specific, the [`AWS policy tools`](https://github.com/kdeldycke/awesome-iam#aws-policy-tools) section is appropriate.

Feel free to create a PR, I'll merge it.
