### ISSUE TITLE
You seems to be missing a12n-server in your otherwise excellent collection

### ISSUE THREAD

**Issue by trasherdk** [kdeldycke/awesome-iam#91]
#### Preliminary checks

- [X] I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-iam/blob/main/.github/code-of-conduct.md)
- [X] I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-iam/blob/main/.github/contributing.md)
- [X] I have checked there is not other [Issues](https://github.com/kdeldycke/awesome-iam/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-iam/pulls) covering the same topic to open

#### Summary

You seems to be missing [a12n-server](https://github.com/curveball/a12n-server) in your otherwise excellent collection :smiley: 

Authentication API
==================

This package aims to provide a simple authentication system. The goal is to
provide a simple authentication system for developers considering building
their own.

The project implements OAuth2 standards where applicable.

![a12n-server home screenshot](https://raw.githubusercontent.com/curveball/a12n-server/master/docs/screenshot-0.19.png)

**Comment by trasherdk** [comment]
BTW. Don't test until https://github.com/curveball/a12n-server/pull/373 have been merged :laughing:

**Comment by kdeldycke** [comment]
OK, fair enough. Let's add it! :)
